### PR TITLE
React server side rendering support.

### PR DESCRIPTION
**Pull request by hanjukim**
* Require 'pullhelper' in componentDidMount for React server side rendering (also known as isomorphic or universal rendering)
* Remove webpacked file from repo and add npm script `prepare` for build.
* Remove style-loader since it seems to be not needed. (style-loader also breaks SSR too)
* Convert spaces to tabs. :)

### CODE REVIEW

**Comment by yusukeshibata** [comment]
Thanks merged.

**Comment by yusukeshibata** [comment]
And published to npm as 1.1.7.

**Comment by hanjukim** [comment]
@yusukeshibata Current published v1.1.7 package have a problem that does not have index.js (build output) file.
Could you please use npm v4.x for publishing? npm v3.x does not recongnize 'prepare' script that should run before publishing.

**Comment by yusukeshibata** [comment]
republished: v1.1.8

**Pull request merged**
